import { useMemo } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Download, FileText, FileSpreadsheet, FileType2, ArrowUp } from "lucide-react";
import { toast } from "@/hooks/use-toast";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { ReportData, ReportSectionData } from "@/lib/reportAnalytics";

export interface ReportPreviewData {
  id: string;
  name: string;
  template: string;
  period: string;
  format: string;
  size: string;
  sections?: string[];
  data?: ReportData;
  whitelabel?: boolean;
}

interface ReportPreviewDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  report: ReportPreviewData | null;
}

function safeName(n: string) {
  return n.replace(/[^\w-]+/g, "_");
}

function downloadPdf(report: ReportPreviewData) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const width = doc.internal.pageSize.getWidth();
  let y = 48;

  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(report.name, 40, y);
  y += 24;
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120);
  doc.text(`${report.template} · ${report.period}`, 40, y);
  y += 8;
  doc.setDrawColor(220);
  doc.line(40, y + 6, width - 40, y + 6);
  y += 24;
  doc.setTextColor(20);

  if (report.data) {
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Summary", 40, y);
    y += 16;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    autoTable(doc, {
      startY: y,
      head: [["Metric", "Value"]],
      body: [
        ["Total followers", report.data.totalFollowers.toLocaleString()],
        ["Total engagement", report.data.totalEngagement.toLocaleString()],
        ["Total reach", report.data.totalReach.toLocaleString()],
        ["Platforms", `${report.data.platformBreakdown.length}`],
      ],
      styles: { fontSize: 10 },
      headStyles: { fillColor: [37, 99, 235] },
      margin: { left: 40, right: 40 },
    });
    // @ts-expect-error - autoTable extends doc
    y = (doc.lastAutoTable?.finalY ?? y) + 20;

    report.data.sections.forEach((s: ReportSectionData) => {
      if (y > 720) {
        doc.addPage();
        y = 48;
      }
      doc.setFontSize(13);
      doc.setFont("helvetica", "bold");
      doc.text(s.section, 40, y);
      y += 14;
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(90);
      const lines = doc.splitTextToSize(s.summary, width - 80);
      doc.text(lines, 40, y);
      y += lines.length * 12 + 6;
      doc.setTextColor(20);
      autoTable(doc, {
        startY: y,
        head: [["Metric", "Value", "Change"]],
        body: s.metrics.map((m) => [m.label, m.value, m.delta ?? "—"]),
        styles: { fontSize: 10 },
        headStyles: { fillColor: [37, 99, 235] },
        margin: { left: 40, right: 40 },
      });
      // @ts-expect-error - autoTable extends doc
      y = (doc.lastAutoTable?.finalY ?? y) + 20;
    });
  }

  if (!report.whitelabel) {
    const pages = doc.getNumberOfPages();
    for (let i = 1; i <= pages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(
        `Generated by SMMSAAS · ${new Date(report.data?.generatedAt ?? Date.now()).toLocaleString()} · Page ${i}/${pages}`,
        40,
        doc.internal.pageSize.getHeight() - 20,
      );
    }
  }

  doc.save(`${safeName(report.name)}.pdf`);
}

function downloadCsv(report: ReportPreviewData) {
  const rows: string[] = [["Section", "Metric", "Value", "Change"].join(",")];
  report.data?.sections.forEach((s) => {
    s.metrics.forEach((m) => {
      rows.push(
        [s.section, m.label, m.value, m.delta ?? ""].map((v) => `"${String(v).replace(/"/g, '""')}"`).join(","),
      );
    });
  });
  const blob = new Blob([rows.join("\n")], { type: "text/csv" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${safeName(report.name)}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

function downloadText(report: ReportPreviewData) {
  const parts = [
    `Report: ${report.name}`,
    `Template: ${report.template}`,
    `Period: ${report.period}`,
    "",
  ];
  report.data?.sections.forEach((s) => {
    parts.push(`## ${s.section}`);
    parts.push(s.summary);
    s.metrics.forEach((m) => parts.push(`- ${m.label}: ${m.value}${m.delta ? ` (${m.delta})` : ""}`));
    parts.push("");
  });
  const blob = new Blob([parts.join("\n")], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${safeName(report.name)}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export function ReportPreviewDialog({ open, onOpenChange, report }: ReportPreviewDialogProps) {
  const data = report?.data;

  const kpis = useMemo(() => {
    if (!data) return [];
    return [
      { label: "Followers", value: data.totalFollowers.toLocaleString() },
      { label: "Engagement", value: data.totalEngagement.toLocaleString() },
      { label: "Reach", value: data.totalReach.toLocaleString() },
      { label: "Platforms", value: `${data.platformBreakdown.length}` },
    ];
  }, [data]);

  if (!report) return null;

  const download = (fmt: string) => {
    if (fmt === "pdf") downloadPdf(report);
    else if (fmt === "csv" || fmt === "excel") downloadCsv(report);
    else downloadText(report);
    toast({ title: "Download started", description: `${report.name} · ${fmt.toUpperCase()}` });
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-primary" />
            {report.name}
          </DialogTitle>
          <DialogDescription>
            {report.template} · {report.period} · {report.size}
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            {kpis.map((k) => (
              <div key={k.label} className="rounded-lg border bg-muted/30 p-3">
                <p className="text-xs text-muted-foreground">{k.label}</p>
                <p className="text-lg font-semibold mt-1">{k.value}</p>
              </div>
            ))}
          </div>

          <div className="space-y-3">
            {data?.sections.map((s) => (
              <div key={s.section} className="rounded-lg border p-4 space-y-3">
                <div>
                  <h4 className="font-semibold text-sm">{s.section}</h4>
                  <p className="text-xs text-muted-foreground mt-0.5">{s.summary}</p>
                </div>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
                  {s.metrics.map((m) => (
                    <div key={m.label} className="rounded border bg-card p-2">
                      <p className="text-[11px] text-muted-foreground truncate">{m.label}</p>
                      <p className="text-sm font-semibold mt-0.5">{m.value}</p>
                      {m.delta && (
                        <p
                          className={`text-[10px] flex items-center gap-0.5 mt-0.5 ${
                            m.positive === false ? "text-destructive" : "text-emerald-500"
                          }`}
                        >
                          <ArrowUp className="h-2.5 w-2.5" />
                          {m.delta}
                        </p>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            ))}
            {!data?.sections.length && (
              <p className="text-sm text-muted-foreground text-center py-8">
                No sections in this report.
              </p>
            )}
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <Badge variant="outline" className="uppercase">
              {report.format}
            </Badge>
            <Badge variant="secondary">{(report.sections ?? []).length} sections</Badge>
            {report.whitelabel && <Badge variant="secondary">White-label</Badge>}
          </div>
        </div>

        <DialogFooter className="flex-wrap gap-2">
          <Button variant="ghost" onClick={() => onOpenChange(false)}>
            Close
          </Button>
          <Button variant="outline" onClick={() => download("txt")}>
            <FileText className="mr-2 h-4 w-4" />
            Text
          </Button>
          <Button variant="outline" onClick={() => download("csv")}>
            <FileSpreadsheet className="mr-2 h-4 w-4" />
            CSV
          </Button>
          <Button onClick={() => download("pdf")}>
            <FileType2 className="mr-2 h-4 w-4" />
            Download PDF
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
