export interface LinkBioTheme {
  id: string;
  name: string;
  tagline: string;
  bg: string; // tailwind bg for preview canvas
  accent: string; // hex
  buttonClass: string;
  textClass: string;
  subTextClass: string;
  fontClass: string;
  radius: "sm" | "md" | "xl" | "full";
  buttonStyle: "solid" | "outline" | "pill" | "glass" | "brutal";
}

export const linkBioThemes: LinkBioTheme[] = [
  {
    id: "midnight-glass",
    name: "Midnight Glass",
    tagline: "Deep navy with frosted glass buttons",
    bg: "bg-gradient-to-b from-slate-900 via-slate-950 to-black",
    accent: "#6366f1",
    buttonClass: "bg-white/10 hover:bg-white/20 backdrop-blur-md border border-white/15 text-white",
    textClass: "text-white",
    subTextClass: "text-slate-300",
    fontClass: "font-sans",
    radius: "xl",
    buttonStyle: "glass",
  },
  {
    id: "sunset-gradient",
    name: "Sunset Gradient",
    tagline: "Warm orange to magenta blend",
    bg: "bg-gradient-to-br from-orange-400 via-rose-500 to-purple-600",
    accent: "#ec4899",
    buttonClass: "bg-white/20 hover:bg-white/30 backdrop-blur-sm border border-white/30 text-white",
    textClass: "text-white",
    subTextClass: "text-white/90",
    fontClass: "font-sans",
    radius: "full",
    buttonStyle: "pill",
  },
  {
    id: "paper-minimal",
    name: "Paper Minimal",
    tagline: "Editorial cream with black ink",
    bg: "bg-[#f5f3ee]",
    accent: "#0d0d0d",
    buttonClass: "bg-white hover:bg-neutral-50 border border-neutral-300 text-neutral-900 shadow-sm",
    textClass: "text-neutral-900",
    subTextClass: "text-neutral-600",
    fontClass: "font-serif",
    radius: "sm",
    buttonStyle: "outline",
  },
  {
    id: "neon-retro",
    name: "Neon Retro",
    tagline: "Cyberpunk glow, arcade energy",
    bg: "bg-[radial-gradient(ellipse_at_top,_#1e1b4b,_#000)]",
    accent: "#22d3ee",
    buttonClass: "bg-cyan-400/10 hover:bg-cyan-400/20 border border-cyan-400/40 text-cyan-100 shadow-[0_0_20px_rgba(34,211,238,0.35)]",
    textClass: "text-white",
    subTextClass: "text-cyan-200/80",
    fontClass: "font-mono",
    radius: "md",
    buttonStyle: "solid",
  },
  {
    id: "pastel-cloud",
    name: "Pastel Cloud",
    tagline: "Soft sky with peach highlights",
    bg: "bg-gradient-to-b from-sky-100 via-rose-50 to-orange-100",
    accent: "#f9a8a8",
    buttonClass: "bg-white/70 hover:bg-white border border-rose-200 text-rose-900 backdrop-blur-sm",
    textClass: "text-rose-950",
    subTextClass: "text-rose-700",
    fontClass: "font-sans",
    radius: "full",
    buttonStyle: "pill",
  },
  {
    id: "terracotta",
    name: "Terracotta",
    tagline: "Warm clay and sage tones",
    bg: "bg-gradient-to-b from-orange-200 via-orange-300 to-amber-400",
    accent: "#c4654a",
    buttonClass: "bg-white/80 hover:bg-white border border-orange-300 text-orange-950",
    textClass: "text-orange-950",
    subTextClass: "text-orange-800",
    fontClass: "font-serif",
    radius: "md",
    buttonStyle: "solid",
  },
  {
    id: "mono-noir",
    name: "Mono Noir",
    tagline: "Pure black with gold accents",
    bg: "bg-black",
    accent: "#c9a84c",
    buttonClass: "bg-neutral-900 hover:bg-neutral-800 border border-yellow-500/40 text-yellow-100",
    textClass: "text-white",
    subTextClass: "text-neutral-400",
    fontClass: "font-serif",
    radius: "sm",
    buttonStyle: "outline",
  },
  {
    id: "ocean-deep",
    name: "Ocean Deep",
    tagline: "Calm teals and deep navy",
    bg: "bg-gradient-to-b from-cyan-500 via-blue-600 to-indigo-800",
    accent: "#0ea5e9",
    buttonClass: "bg-white/15 hover:bg-white/25 backdrop-blur-md border border-white/20 text-white",
    textClass: "text-white",
    subTextClass: "text-cyan-50",
    fontClass: "font-sans",
    radius: "xl",
    buttonStyle: "glass",
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    tagline: "Hot pink over inky black",
    bg: "bg-gradient-to-br from-fuchsia-600 via-black to-purple-900",
    accent: "#e879f9",
    buttonClass: "bg-black/60 hover:bg-black/80 border-2 border-fuchsia-400/70 text-fuchsia-100 shadow-[0_0_16px_rgba(232,121,249,0.4)]",
    textClass: "text-fuchsia-50",
    subTextClass: "text-fuchsia-200/80",
    fontClass: "font-mono",
    radius: "sm",
    buttonStyle: "brutal",
  },
  {
    id: "y2k-chrome",
    name: "Y2K Chrome",
    tagline: "Iridescent pastels, chrome shine",
    bg: "bg-gradient-to-br from-violet-300 via-sky-200 to-cyan-200",
    accent: "#a78bfa",
    buttonClass: "bg-white/60 hover:bg-white/80 border border-white text-slate-900 backdrop-blur-md shadow-lg",
    textClass: "text-slate-900",
    subTextClass: "text-slate-700",
    fontClass: "font-sans",
    radius: "full",
    buttonStyle: "glass",
  },
  {
    id: "forest-cottage",
    name: "Forest Cottage",
    tagline: "Mossy greens and warm cream",
    bg: "bg-gradient-to-b from-emerald-800 via-emerald-900 to-green-950",
    accent: "#a0c49d",
    buttonClass: "bg-emerald-100/10 hover:bg-emerald-100/20 border border-emerald-200/30 text-emerald-50",
    textClass: "text-emerald-50",
    subTextClass: "text-emerald-200/80",
    fontClass: "font-serif",
    radius: "md",
    buttonStyle: "outline",
  },
  {
    id: "editorial-serif",
    name: "Editorial Serif",
    tagline: "Magazine-inspired, serif elegance",
    bg: "bg-gradient-to-b from-neutral-100 to-neutral-200",
    accent: "#1f2937",
    buttonClass: "bg-neutral-900 hover:bg-neutral-800 text-white border border-neutral-900",
    textClass: "text-neutral-900",
    subTextClass: "text-neutral-600",
    fontClass: "font-serif",
    radius: "sm",
    buttonStyle: "solid",
  },
  // ── Phase 2 — Editorial & Premium ──
  {
    id: "vogue-column",
    name: "Vogue Column",
    tagline: "High-fashion editorial with condensed serif",
    bg: "bg-[#f8f5f0]",
    accent: "#111111",
    buttonClass: "bg-black hover:bg-neutral-800 text-white",
    textClass: "text-neutral-900",
    subTextClass: "text-neutral-500",
    fontClass: "font-serif",
    radius: "sm",
    buttonStyle: "solid",
  },
  {
    id: "kinfolk-cream",
    name: "Kinfolk Cream",
    tagline: "Muted cream, generous whitespace",
    bg: "bg-[#efe9df]",
    accent: "#8a7a63",
    buttonClass: "bg-white/70 hover:bg-white border border-neutral-300 text-neutral-800",
    textClass: "text-neutral-800",
    subTextClass: "text-neutral-500",
    fontClass: "font-serif",
    radius: "sm",
    buttonStyle: "outline",
  },
  {
    id: "swiss-grid",
    name: "Swiss Grid",
    tagline: "Bauhaus grid, precise sans",
    bg: "bg-white",
    accent: "#e53935",
    buttonClass: "bg-black hover:bg-neutral-800 text-white",
    textClass: "text-neutral-900",
    subTextClass: "text-neutral-500",
    fontClass: "font-sans",
    radius: "sm",
    buttonStyle: "solid",
  },
  {
    id: "brutalist-zine",
    name: "Brutalist Zine",
    tagline: "Raw, high-contrast, hard shadows",
    bg: "bg-yellow-300",
    accent: "#000000",
    buttonClass: "bg-white hover:bg-neutral-100 text-black border-2 border-black shadow-[4px_4px_0_0_rgba(0,0,0,1)]",
    textClass: "text-black",
    subTextClass: "text-neutral-800",
    fontClass: "font-mono",
    radius: "sm",
    buttonStyle: "brutal",
  },
  {
    id: "gold-foil",
    name: "Gold Foil",
    tagline: "Deep black with gilded accents",
    bg: "bg-gradient-to-b from-neutral-950 to-black",
    accent: "#d4af37",
    buttonClass: "bg-transparent hover:bg-yellow-500/10 border border-yellow-400/70 text-yellow-100",
    textClass: "text-yellow-50",
    subTextClass: "text-yellow-200/70",
    fontClass: "font-serif",
    radius: "sm",
    buttonStyle: "outline",
  },
  {
    id: "monochrome-fashion",
    name: "Monochrome Fashion",
    tagline: "Cool grays, runway minimal",
    bg: "bg-gradient-to-b from-neutral-200 to-neutral-300",
    accent: "#111111",
    buttonClass: "bg-neutral-900 hover:bg-black text-white",
    textClass: "text-neutral-900",
    subTextClass: "text-neutral-600",
    fontClass: "font-sans",
    radius: "md",
    buttonStyle: "solid",
  },
  {
    id: "gallery-wall",
    name: "Gallery Wall",
    tagline: "Warm off-white with framed accents",
    bg: "bg-[#f2ede4]",
    accent: "#6b4f2c",
    buttonClass: "bg-white hover:bg-neutral-50 border border-neutral-400 text-neutral-800",
    textClass: "text-neutral-900",
    subTextClass: "text-neutral-500",
    fontClass: "font-serif",
    radius: "md",
    buttonStyle: "outline",
  },
  {
    id: "newsprint",
    name: "Newsprint",
    tagline: "Broadsheet grays with red masthead",
    bg: "bg-[#f4f1ea]",
    accent: "#c62828",
    buttonClass: "bg-neutral-900 hover:bg-black text-white",
    textClass: "text-neutral-900",
    subTextClass: "text-neutral-600",
    fontClass: "font-serif",
    radius: "sm",
    buttonStyle: "solid",
  },
  {
    id: "silk-ribbon",
    name: "Silk Ribbon",
    tagline: "Blush satin with rose gold",
    bg: "bg-gradient-to-br from-rose-100 via-pink-100 to-rose-200",
    accent: "#b76e79",
    buttonClass: "bg-white/80 hover:bg-white border border-rose-300 text-rose-900 backdrop-blur-sm",
    textClass: "text-rose-950",
    subTextClass: "text-rose-700",
    fontClass: "font-serif",
    radius: "full",
    buttonStyle: "pill",
  },
  {
    id: "aurora-flow",
    name: "Aurora Flow",
    tagline: "Motion-first gradient aurora",
    bg: "bg-[conic-gradient(from_180deg_at_50%_50%,_#4ade80,_#a78bfa,_#22d3ee,_#4ade80)]",
    accent: "#a78bfa",
    buttonClass: "bg-white/15 hover:bg-white/25 backdrop-blur-md border border-white/25 text-white",
    textClass: "text-white",
    subTextClass: "text-white/80",
    fontClass: "font-sans",
    radius: "xl",
    buttonStyle: "glass",
  },
];

export const THEME_STORAGE_KEY = "smmpilot:linkbio:active-theme";

export function loadActiveThemeId(): string {
  if (typeof window === "undefined") return linkBioThemes[0].id;
  return localStorage.getItem(THEME_STORAGE_KEY) || linkBioThemes[0].id;
}
