export type ThemePhase = 1 | 2 | 3 | 4;

export interface LinkBioTheme {
  id: string;
  name: string;
  tagline: string;
  bg: string; // tailwind bg for preview canvas
  accent: string; // hex
  buttonClass: string;
  textClass: string;
  subTextClass: string;
  fontClass: string;
  radius: "sm" | "md" | "xl" | "full";
  buttonStyle: "solid" | "outline" | "pill" | "glass" | "brutal";
  phase?: ThemePhase;
}

export const phaseMeta: Record<ThemePhase, { title: string; blurb: string }> = {
  1: { title: "Foundations", blurb: "Core versatile looks for any creator." },
  2: { title: "Editorial & Premium", blurb: "Fashion, print and luxury inspired." },
  3: { title: "Motion & Immersive", blurb: "Gradients, glass and animated depth." },
  4: { title: "Niche & Playful", blurb: "Bold, indie and character-driven." },
};


export const linkBioThemes: LinkBioTheme[] = [
  {
    id: "midnight-glass",
    name: "Midnight Glass",
    tagline: "Deep navy with frosted glass buttons",
    bg: "bg-gradient-to-b from-slate-900 via-slate-950 to-black",
    accent: "#6366f1",
    buttonClass: "bg-white/10 hover:bg-white/20 backdrop-blur-md border border-white/15 text-white",
    textClass: "text-white",
    subTextClass: "text-slate-300",
    fontClass: "font-sans",
    radius: "xl",
    buttonStyle: "glass",
  },
  {
    id: "sunset-gradient",
    name: "Sunset Gradient",
    tagline: "Warm orange to magenta blend",
    bg: "bg-gradient-to-br from-orange-400 via-rose-500 to-purple-600",
    accent: "#ec4899",
    buttonClass: "bg-white/20 hover:bg-white/30 backdrop-blur-sm border border-white/30 text-white",
    textClass: "text-white",
    subTextClass: "text-white/90",
    fontClass: "font-sans",
    radius: "full",
    buttonStyle: "pill",
  },
  {
    id: "paper-minimal",
    name: "Paper Minimal",
    tagline: "Editorial cream with black ink",
    bg: "bg-[#f5f3ee]",
    accent: "#0d0d0d",
    buttonClass: "bg-white hover:bg-neutral-50 border border-neutral-300 text-neutral-900 shadow-sm",
    textClass: "text-neutral-900",
    subTextClass: "text-neutral-600",
    fontClass: "font-serif",
    radius: "sm",
    buttonStyle: "outline",
  },
  {
    id: "neon-retro",
    name: "Neon Retro",
    tagline: "Cyberpunk glow, arcade energy",
    bg: "bg-[radial-gradient(ellipse_at_top,_#1e1b4b,_#000)]",
    accent: "#22d3ee",
    buttonClass: "bg-cyan-400/10 hover:bg-cyan-400/20 border border-cyan-400/40 text-cyan-100 shadow-[0_0_20px_rgba(34,211,238,0.35)]",
    textClass: "text-white",
    subTextClass: "text-cyan-200/80",
    fontClass: "font-mono",
    radius: "md",
    buttonStyle: "solid",
  },
  {
    id: "pastel-cloud",
    name: "Pastel Cloud",
    tagline: "Soft sky with peach highlights",
    bg: "bg-gradient-to-b from-sky-100 via-rose-50 to-orange-100",
    accent: "#f9a8a8",
    buttonClass: "bg-white/70 hover:bg-white border border-rose-200 text-rose-900 backdrop-blur-sm",
    textClass: "text-rose-950",
    subTextClass: "text-rose-700",
    fontClass: "font-sans",
    radius: "full",
    buttonStyle: "pill",
  },
  {
    id: "terracotta",
    name: "Terracotta",
    tagline: "Warm clay and sage tones",
    bg: "bg-gradient-to-b from-orange-200 via-orange-300 to-amber-400",
    accent: "#c4654a",
    buttonClass: "bg-white/80 hover:bg-white border border-orange-300 text-orange-950",
    textClass: "text-orange-950",
    subTextClass: "text-orange-800",
    fontClass: "font-serif",
    radius: "md",
    buttonStyle: "solid",
  },
  {
    id: "mono-noir",
    name: "Mono Noir",
    tagline: "Pure black with gold accents",
    bg: "bg-black",
    accent: "#c9a84c",
    buttonClass: "bg-neutral-900 hover:bg-neutral-800 border border-yellow-500/40 text-yellow-100",
    textClass: "text-white",
    subTextClass: "text-neutral-400",
    fontClass: "font-serif",
    radius: "sm",
    buttonStyle: "outline",
  },
  {
    id: "ocean-deep",
    name: "Ocean Deep",
    tagline: "Calm teals and deep navy",
    bg: "bg-gradient-to-b from-cyan-500 via-blue-600 to-indigo-800",
    accent: "#0ea5e9",
    buttonClass: "bg-white/15 hover:bg-white/25 backdrop-blur-md border border-white/20 text-white",
    textClass: "text-white",
    subTextClass: "text-cyan-50",
    fontClass: "font-sans",
    radius: "xl",
    buttonStyle: "glass",
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    tagline: "Hot pink over inky black",
    bg: "bg-gradient-to-br from-fuchsia-600 via-black to-purple-900",
    accent: "#e879f9",
    buttonClass: "bg-black/60 hover:bg-black/80 border-2 border-fuchsia-400/70 text-fuchsia-100 shadow-[0_0_16px_rgba(232,121,249,0.4)]",
    textClass: "text-fuchsia-50",
    subTextClass: "text-fuchsia-200/80",
    fontClass: "font-mono",
    radius: "sm",
    buttonStyle: "brutal",
  },
  {
    id: "y2k-chrome",
    name: "Y2K Chrome",
    tagline: "Iridescent pastels, chrome shine",
    bg: "bg-gradient-to-br from-violet-300 via-sky-200 to-cyan-200",
    accent: "#a78bfa",
    buttonClass: "bg-white/60 hover:bg-white/80 border border-white text-slate-900 backdrop-blur-md shadow-lg",
    textClass: "text-slate-900",
    subTextClass: "text-slate-700",
    fontClass: "font-sans",
    radius: "full",
    buttonStyle: "glass",
  },
  {
    id: "forest-cottage",
    name: "Forest Cottage",
    tagline: "Mossy greens and warm cream",
    bg: "bg-gradient-to-b from-emerald-800 via-emerald-900 to-green-950",
    accent: "#a0c49d",
    buttonClass: "bg-emerald-100/10 hover:bg-emerald-100/20 border border-emerald-200/30 text-emerald-50",
    textClass: "text-emerald-50",
    subTextClass: "text-emerald-200/80",
    fontClass: "font-serif",
    radius: "md",
    buttonStyle: "outline",
  },
  {
    id: "editorial-serif",
    name: "Editorial Serif",
    tagline: "Magazine-inspired, serif elegance",
    bg: "bg-gradient-to-b from-neutral-100 to-neutral-200",
    accent: "#1f2937",
    buttonClass: "bg-neutral-900 hover:bg-neutral-800 text-white border border-neutral-900",
    textClass: "text-neutral-900",
    subTextClass: "text-neutral-600",
    fontClass: "font-serif",
    radius: "sm",
    buttonStyle: "solid",
  },
  // ── Phase 2 — Editorial & Premium ──
  {
    id: "vogue-column",
    name: "Vogue Column",
    tagline: "High-fashion editorial with condensed serif",
    bg: "bg-[#f8f5f0]",
    accent: "#111111",
    buttonClass: "bg-black hover:bg-neutral-800 text-white",
    textClass: "text-neutral-900",
    subTextClass: "text-neutral-500",
    fontClass: "font-serif",
    radius: "sm",
    buttonStyle: "solid",
  },
  {
    id: "kinfolk-cream",
    name: "Kinfolk Cream",
    tagline: "Muted cream, generous whitespace",
    bg: "bg-[#efe9df]",
    accent: "#8a7a63",
    buttonClass: "bg-white/70 hover:bg-white border border-neutral-300 text-neutral-800",
    textClass: "text-neutral-800",
    subTextClass: "text-neutral-500",
    fontClass: "font-serif",
    radius: "sm",
    buttonStyle: "outline",
  },
  {
    id: "swiss-grid",
    name: "Swiss Grid",
    tagline: "Bauhaus grid, precise sans",
    bg: "bg-white",
    accent: "#e53935",
    buttonClass: "bg-black hover:bg-neutral-800 text-white",
    textClass: "text-neutral-900",
    subTextClass: "text-neutral-500",
    fontClass: "font-sans",
    radius: "sm",
    buttonStyle: "solid",
  },
  {
    id: "brutalist-zine",
    name: "Brutalist Zine",
    tagline: "Raw, high-contrast, hard shadows",
    bg: "bg-yellow-300",
    accent: "#000000",
    buttonClass: "bg-white hover:bg-neutral-100 text-black border-2 border-black shadow-[4px_4px_0_0_rgba(0,0,0,1)]",
    textClass: "text-black",
    subTextClass: "text-neutral-800",
    fontClass: "font-mono",
    radius: "sm",
    buttonStyle: "brutal",
  },
  {
    id: "gold-foil",
    name: "Gold Foil",
    tagline: "Deep black with gilded accents",
    bg: "bg-gradient-to-b from-neutral-950 to-black",
    accent: "#d4af37",
    buttonClass: "bg-transparent hover:bg-yellow-500/10 border border-yellow-400/70 text-yellow-100",
    textClass: "text-yellow-50",
    subTextClass: "text-yellow-200/70",
    fontClass: "font-serif",
    radius: "sm",
    buttonStyle: "outline",
  },
  {
    id: "monochrome-fashion",
    name: "Monochrome Fashion",
    tagline: "Cool grays, runway minimal",
    bg: "bg-gradient-to-b from-neutral-200 to-neutral-300",
    accent: "#111111",
    buttonClass: "bg-neutral-900 hover:bg-black text-white",
    textClass: "text-neutral-900",
    subTextClass: "text-neutral-600",
    fontClass: "font-sans",
    radius: "md",
    buttonStyle: "solid",
  },
  {
    id: "gallery-wall",
    name: "Gallery Wall",
    tagline: "Warm off-white with framed accents",
    bg: "bg-[#f2ede4]",
    accent: "#6b4f2c",
    buttonClass: "bg-white hover:bg-neutral-50 border border-neutral-400 text-neutral-800",
    textClass: "text-neutral-900",
    subTextClass: "text-neutral-500",
    fontClass: "font-serif",
    radius: "md",
    buttonStyle: "outline",
  },
  {
    id: "newsprint",
    name: "Newsprint",
    tagline: "Broadsheet grays with red masthead",
    bg: "bg-[#f4f1ea]",
    accent: "#c62828",
    buttonClass: "bg-neutral-900 hover:bg-black text-white",
    textClass: "text-neutral-900",
    subTextClass: "text-neutral-600",
    fontClass: "font-serif",
    radius: "sm",
    buttonStyle: "solid",
  },
  {
    id: "silk-ribbon",
    name: "Silk Ribbon",
    tagline: "Blush satin with rose gold",
    bg: "bg-gradient-to-br from-rose-100 via-pink-100 to-rose-200",
    accent: "#b76e79",
    buttonClass: "bg-white/80 hover:bg-white border border-rose-300 text-rose-900 backdrop-blur-sm",
    textClass: "text-rose-950",
    subTextClass: "text-rose-700",
    fontClass: "font-serif",
    radius: "full",
    buttonStyle: "pill",
  },
  {
    id: "aurora-flow",
    name: "Aurora Flow",
    tagline: "Motion-first gradient aurora",
    bg: "bg-[conic-gradient(from_180deg_at_50%_50%,_#4ade80,_#a78bfa,_#22d3ee,_#4ade80)]",
    accent: "#a78bfa",
    buttonClass: "bg-white/15 hover:bg-white/25 backdrop-blur-md border border-white/25 text-white",
    textClass: "text-white",
    subTextClass: "text-white/80",
    fontClass: "font-sans",
    radius: "xl",
    buttonStyle: "glass",
  },
];

  // ── Phase 3 — Motion & Immersive ──
  {
    id: "liquid-mercury",
    name: "Liquid Mercury",
    tagline: "Chrome liquid gradient in motion",
    bg: "bg-[conic-gradient(from_45deg_at_50%_50%,_#e2e8f0,_#94a3b8,_#0f172a,_#94a3b8,_#e2e8f0)]",
    accent: "#94a3b8",
    buttonClass: "bg-white/20 hover:bg-white/30 backdrop-blur-md border border-white/30 text-white",
    textClass: "text-white",
    subTextClass: "text-slate-100",
    fontClass: "font-sans",
    radius: "full",
    buttonStyle: "glass",
    phase: 3,
  },
  {
    id: "holographic",
    name: "Holographic",
    tagline: "Iridescent foil, prism shine",
    bg: "bg-[linear-gradient(135deg,_#fbcfe8,_#a5f3fc,_#c7d2fe,_#fde68a)]",
    accent: "#c084fc",
    buttonClass: "bg-white/40 hover:bg-white/60 backdrop-blur-md border border-white/60 text-slate-900",
    textClass: "text-slate-900",
    subTextClass: "text-slate-700",
    fontClass: "font-sans",
    radius: "xl",
    buttonStyle: "glass",
    phase: 3,
  },
  {
    id: "deep-space",
    name: "Deep Space",
    tagline: "Nebula purples over cosmic black",
    bg: "bg-[radial-gradient(ellipse_at_top_right,_#4c1d95,_#0f172a_60%,_#000)]",
    accent: "#818cf8",
    buttonClass: "bg-indigo-500/15 hover:bg-indigo-500/25 backdrop-blur-md border border-indigo-400/30 text-indigo-50",
    textClass: "text-indigo-50",
    subTextClass: "text-indigo-200/80",
    fontClass: "font-sans",
    radius: "xl",
    buttonStyle: "glass",
    phase: 3,
  },
  {
    id: "vaporwave",
    name: "Vaporwave",
    tagline: "80s dream — magenta grid, teal sun",
    bg: "bg-gradient-to-b from-fuchsia-500 via-purple-600 to-cyan-500",
    accent: "#f0abfc",
    buttonClass: "bg-white/15 hover:bg-white/25 backdrop-blur-md border border-fuchsia-200/40 text-white",
    textClass: "text-white",
    subTextClass: "text-fuchsia-100",
    fontClass: "font-mono",
    radius: "md",
    buttonStyle: "glass",
    phase: 3,
  },
  {
    id: "aurora-borealis",
    name: "Aurora Borealis",
    tagline: "Green-teal ribbons over midnight sky",
    bg: "bg-[linear-gradient(160deg,_#022c22,_#065f46,_#0e7490,_#1e1b4b)]",
    accent: "#4ade80",
    buttonClass: "bg-emerald-400/10 hover:bg-emerald-400/20 border border-emerald-300/30 text-emerald-50",
    textClass: "text-emerald-50",
    subTextClass: "text-emerald-200/80",
    fontClass: "font-sans",
    radius: "xl",
    buttonStyle: "glass",
    phase: 3,
  },
  {
    id: "glassmorph-ice",
    name: "Glassmorph Ice",
    tagline: "Frosted blue with heavy blur",
    bg: "bg-gradient-to-br from-sky-300 via-blue-400 to-indigo-500",
    accent: "#38bdf8",
    buttonClass: "bg-white/25 hover:bg-white/40 backdrop-blur-xl border border-white/40 text-white",
    textClass: "text-white",
    subTextClass: "text-sky-50",
    fontClass: "font-sans",
    radius: "xl",
    buttonStyle: "glass",
    phase: 3,
  },
  {
    id: "sunset-wave",
    name: "Sunset Wave",
    tagline: "Peach-to-violet dusk fade",
    bg: "bg-[linear-gradient(180deg,_#fda4af,_#fb923c,_#7c3aed_90%)]",
    accent: "#fb923c",
    buttonClass: "bg-white/20 hover:bg-white/30 backdrop-blur-md border border-white/30 text-white",
    textClass: "text-white",
    subTextClass: "text-orange-50",
    fontClass: "font-sans",
    radius: "full",
    buttonStyle: "pill",
    phase: 3,
  },
  {
    id: "matrix-rain",
    name: "Matrix Rain",
    tagline: "Terminal green over abyssal black",
    bg: "bg-[radial-gradient(ellipse_at_center,_#052e16,_#000)]",
    accent: "#22c55e",
    buttonClass: "bg-black hover:bg-neutral-900 border border-green-500/50 text-green-300 shadow-[0_0_16px_rgba(34,197,94,0.35)]",
    textClass: "text-green-300",
    subTextClass: "text-green-500/80",
    fontClass: "font-mono",
    radius: "sm",
    buttonStyle: "outline",
    phase: 3,
  },
  {
    id: "gradient-mesh",
    name: "Gradient Mesh",
    tagline: "Smooth multi-stop mesh gradient",
    bg: "bg-[radial-gradient(at_20%_20%,_#f472b6,_transparent_50%),radial-gradient(at_80%_10%,_#60a5fa,_transparent_50%),radial-gradient(at_50%_80%,_#a78bfa,_transparent_60%),#0f172a]",
    accent: "#f472b6",
    buttonClass: "bg-white/15 hover:bg-white/25 backdrop-blur-md border border-white/25 text-white",
    textClass: "text-white",
    subTextClass: "text-white/80",
    fontClass: "font-sans",
    radius: "xl",
    buttonStyle: "glass",
    phase: 3,
  },
  {
    id: "neon-arcade",
    name: "Neon Arcade",
    tagline: "Hot magenta and cyan arcade glow",
    bg: "bg-[radial-gradient(ellipse_at_top,_#3b0764,_#000)]",
    accent: "#f0abfc",
    buttonClass: "bg-black/60 hover:bg-black/80 border-2 border-fuchsia-400/70 text-fuchsia-100 shadow-[0_0_20px_rgba(232,121,249,0.5)]",
    textClass: "text-fuchsia-50",
    subTextClass: "text-cyan-200",
    fontClass: "font-mono",
    radius: "sm",
    buttonStyle: "brutal",
    phase: 3,
  },
  // ── Phase 4 — Niche & Playful ──
  {
    id: "sticker-pop",
    name: "Sticker Pop",
    tagline: "Playful pastels with sticker shadows",
    bg: "bg-gradient-to-b from-yellow-100 via-pink-100 to-sky-100",
    accent: "#f472b6",
    buttonClass: "bg-white hover:bg-neutral-50 border-2 border-pink-300 text-neutral-900 shadow-[3px_3px_0_0_rgba(236,72,153,0.6)]",
    textClass: "text-neutral-900",
    subTextClass: "text-neutral-600",
    fontClass: "font-sans",
    radius: "full",
    buttonStyle: "brutal",
    phase: 4,
  },
  {
    id: "kawaii",
    name: "Kawaii",
    tagline: "Soft pinks, rounded and cute",
    bg: "bg-gradient-to-b from-pink-100 via-rose-100 to-pink-200",
    accent: "#ec4899",
    buttonClass: "bg-white hover:bg-pink-50 border border-pink-300 text-pink-900",
    textClass: "text-pink-900",
    subTextClass: "text-pink-700",
    fontClass: "font-sans",
    radius: "full",
    buttonStyle: "pill",
    phase: 4,
  },
  {
    id: "skater-zine",
    name: "Skater Zine",
    tagline: "Punk photocopied energy",
    bg: "bg-[url('data:image/svg+xml;utf8,<svg xmlns=%22http://www.w3.org/2000/svg%22 width=%22100%22 height=%22100%22><rect width=%22100%22 height=%22100%22 fill=%22%23111%22/></svg>')] bg-neutral-900",
    accent: "#f97316",
    buttonClass: "bg-orange-500 hover:bg-orange-400 text-black border-2 border-white shadow-[4px_4px_0_0_rgba(255,255,255,1)]",
    textClass: "text-white",
    subTextClass: "text-orange-200",
    fontClass: "font-mono",
    radius: "sm",
    buttonStyle: "brutal",
    phase: 4,
  },
  {
    id: "botanical",
    name: "Botanical",
    tagline: "Deep greens with warm cream",
    bg: "bg-gradient-to-b from-emerald-900 via-emerald-800 to-lime-900",
    accent: "#bef264",
    buttonClass: "bg-emerald-50/10 hover:bg-emerald-50/20 border border-lime-300/30 text-lime-50",
    textClass: "text-lime-50",
    subTextClass: "text-lime-200/80",
    fontClass: "font-serif",
    radius: "md",
    buttonStyle: "outline",
    phase: 4,
  },
  {
    id: "coffee-shop",
    name: "Coffee Shop",
    tagline: "Warm espresso browns and cream",
    bg: "bg-gradient-to-b from-amber-100 via-orange-100 to-amber-200",
    accent: "#78350f",
    buttonClass: "bg-amber-900 hover:bg-amber-800 text-amber-50 border border-amber-950",
    textClass: "text-amber-950",
    subTextClass: "text-amber-800",
    fontClass: "font-serif",
    radius: "md",
    buttonStyle: "solid",
    phase: 4,
  },
  {
    id: "pixel-arcade",
    name: "Pixel Arcade",
    tagline: "8-bit palette, blocky and bold",
    bg: "bg-[#1a1a2e]",
    accent: "#f2b134",
    buttonClass: "bg-[#f2b134] hover:bg-[#ffcd57] text-[#1a1a2e] border-2 border-[#1a1a2e] shadow-[3px_3px_0_0_#000]",
    textClass: "text-white",
    subTextClass: "text-yellow-200",
    fontClass: "font-mono",
    radius: "sm",
    buttonStyle: "brutal",
    phase: 4,
  },
  {
    id: "surf-club",
    name: "Surf Club",
    tagline: "Ocean teal with sandy warmth",
    bg: "bg-gradient-to-b from-teal-400 via-cyan-500 to-blue-600",
    accent: "#fbbf24",
    buttonClass: "bg-white/25 hover:bg-white/40 backdrop-blur-sm border border-white/40 text-white",
    textClass: "text-white",
    subTextClass: "text-cyan-50",
    fontClass: "font-sans",
    radius: "full",
    buttonStyle: "pill",
    phase: 4,
  },
  {
    id: "gothic-cathedral",
    name: "Gothic Cathedral",
    tagline: "Blackletter serif, blood-red accents",
    bg: "bg-[radial-gradient(ellipse_at_top,_#1c0a0a,_#000)]",
    accent: "#dc2626",
    buttonClass: "bg-transparent hover:bg-red-500/10 border border-red-500/60 text-red-100",
    textClass: "text-red-50",
    subTextClass: "text-red-300/70",
    fontClass: "font-serif",
    radius: "sm",
    buttonStyle: "outline",
    phase: 4,
  },
  {
    id: "candy-shop",
    name: "Candy Shop",
    tagline: "Bright bubblegum joy",
    bg: "bg-gradient-to-br from-pink-400 via-fuchsia-400 to-purple-500",
    accent: "#fde047",
    buttonClass: "bg-yellow-300 hover:bg-yellow-200 text-purple-900 border-2 border-white",
    textClass: "text-white",
    subTextClass: "text-pink-50",
    fontClass: "font-sans",
    radius: "full",
    buttonStyle: "pill",
    phase: 4,
  },
  {
    id: "zen-garden",
    name: "Zen Garden",
    tagline: "Muted stone, quiet minimalism",
    bg: "bg-[#e7e5e0]",
    accent: "#57534e",
    buttonClass: "bg-transparent hover:bg-stone-900/5 border border-stone-400 text-stone-800",
    textClass: "text-stone-900",
    subTextClass: "text-stone-600",
    fontClass: "font-serif",
    radius: "sm",
    buttonStyle: "outline",
    phase: 4,
  },
];

// Tag Phase 1 and Phase 2 entries retroactively (by index) for grouping.
const _phase1Ids = new Set([
  "midnight-glass","sunset-gradient","paper-minimal","neon-retro","pastel-cloud","terracotta",
  "mono-noir","ocean-deep","cyberpunk","y2k-chrome","forest-cottage","editorial-serif",
]);
const _phase2Ids = new Set([
  "vogue-column","kinfolk-cream","swiss-grid","brutalist-zine","gold-foil","monochrome-fashion",
  "gallery-wall","newsprint","silk-ribbon","aurora-flow",
]);
for (const t of linkBioThemes) {
  if (!t.phase) t.phase = _phase1Ids.has(t.id) ? 1 : _phase2Ids.has(t.id) ? 2 : 1;
}

export function themesByPhase(phase: ThemePhase) {
  return linkBioThemes.filter((t) => t.phase === phase);
}

export const THEME_STORAGE_KEY = "smmpilot:linkbio:active-theme";

export function loadActiveThemeId(): string {
  if (typeof window === "undefined") return linkBioThemes[0].id;
  return localStorage.getItem(THEME_STORAGE_KEY) || linkBioThemes[0].id;
}

