// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return identity of the signed-in Lovable app user calling this MCP server.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = {
      userId: ctx.getUserId(),
      email: ctx.getUserEmail(),
      clientId: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-platforms.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
var PLATFORMS = [
  "instagram",
  "facebook",
  "tiktok",
  "youtube",
  "twitter",
  "linkedin",
  "pinterest",
  "snapchat",
  "threads",
  "reddit",
  "discord",
  "telegram",
  "whatsapp",
  "twitch"
];
var list_platforms_default = defineTool2({
  name: "list_platforms",
  title: "List supported platforms",
  description: "Return the list of social platforms this SMM app supports.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    return {
      content: [{ type: "text", text: PLATFORMS.join(", ") }],
      structuredContent: { platforms: PLATFORMS }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ntbtbzssdwkbrfcmqyfc";
var mcp_default = defineMcp({
  name: "smm-app-mcp",
  title: "SMM App MCP",
  version: "0.1.0",
  instructions: "Tools for the SMM app. Use `whoami` to check the signed-in user, and `list_platforms` to see which social networks the app supports.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_platforms_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
