// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return identity of the signed-in Lovable app user calling this MCP server.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = {
      userId: ctx.getUserId(),
      email: ctx.getUserEmail(),
      clientId: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-platforms.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
var PLATFORMS = [
  "instagram",
  "facebook",
  "tiktok",
  "youtube",
  "twitter",
  "linkedin",
  "pinterest",
  "snapchat",
  "threads",
  "reddit",
  "discord",
  "telegram",
  "whatsapp",
  "twitch"
];
var list_platforms_default = defineTool2({
  name: "list_platforms",
  title: "List supported platforms",
  description: "Return the list of social platforms this SMM app supports.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    return {
      content: [{ type: "text", text: PLATFORMS.join(", ") }],
      structuredContent: { platforms: PLATFORMS }
    };
  }
});

// src/lib/mcp/tools/list-scheduled-posts.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_scheduled_posts_default = defineTool3({
  name: "list_scheduled_posts",
  title: "List scheduled posts",
  description: "List the user's scheduled cross-platform posts. Scheduled posts live in the user's browser storage today, so this returns a descriptive placeholder rather than fabricated data.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = {
      posts: [],
      note: "Scheduled posts are stored locally in the user's browser (smmpilot:scheduled-posts). Ask the user to open /dashboard/publish/queue to see them, or use queue_cross_platform_post to add a new one."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/queue-cross-platform-post.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
var SUPPORTED_PLATFORMS = [
  "instagram",
  "facebook",
  "tiktok",
  "youtube",
  "twitter",
  "linkedin",
  "pinterest",
  "snapchat",
  "threads",
  "reddit",
  "discord",
  "telegram",
  "whatsapp",
  "twitch"
];
var queue_cross_platform_post_default = defineTool4({
  name: "queue_cross_platform_post",
  title: "Queue cross-platform post",
  description: "Draft a scheduled cross-platform post plan for the signed-in user. Returns a validated post record ready to be added to the queue on the user's next app open.",
  inputSchema: {
    caption: z.string().min(1).max(4e3).describe("Post caption text."),
    platformIds: z.array(z.string()).min(1).describe("Platforms to publish to. Must come from the app's supported set."),
    scheduledAt: z.string().describe("ISO 8601 timestamp to publish at."),
    hashtags: z.array(z.string()).optional().describe("Hashtags without leading #."),
    mediaUrl: z.string().url().optional().describe("Optional media URL.")
  },
  annotations: {
    readOnlyHint: false,
    destructiveHint: false,
    openWorldHint: false
  },
  handler: (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const unknownPlatforms = input.platformIds.filter((p) => !SUPPORTED_PLATFORMS.includes(p));
    if (unknownPlatforms.length > 0) {
      return {
        content: [
          {
            type: "text",
            text: `Unsupported platforms: ${unknownPlatforms.join(", ")}. Supported: ${SUPPORTED_PLATFORMS.join(", ")}.`
          }
        ],
        isError: true
      };
    }
    const when = new Date(input.scheduledAt);
    if (Number.isNaN(when.getTime())) {
      return { content: [{ type: "text", text: "scheduledAt must be a valid ISO 8601 timestamp." }], isError: true };
    }
    const record = {
      id: crypto.randomUUID(),
      caption: input.caption,
      platformIds: input.platformIds,
      scheduledAt: when.toISOString(),
      hashtags: input.hashtags ?? [],
      mediaUrl: input.mediaUrl,
      createdAt: (/* @__PURE__ */ new Date()).toISOString(),
      status: "pending-approval",
      source: "mcp:queue_cross_platform_post",
      userId: ctx.getUserId()
    };
    return {
      content: [
        {
          type: "text",
          text: `Proposed cross-platform post for ${input.platformIds.join(", ")} at ${when.toISOString()}. The user must approve it inside the app before it is queued.`
        }
      ],
      structuredContent: { post: record, needsApproval: true }
    };
  }
});

// src/lib/mcp/tools/list-captions.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_captions_default = defineTool5({
  name: "list_captions",
  title: "List caption library",
  description: "List saved captions from the user's caption library. Captions are stored in the user's browser today, so this returns a descriptive placeholder. Use `create_caption_draft` to add new drafts that appear next time the user opens the app.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = {
      captions: [],
      note: "Captions live in the user's browser (smmpilot:library:captions). Ask them to open /dashboard/library/captions to see all captions."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/create-caption-draft.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
var create_caption_draft_default = defineTool6({
  name: "create_caption_draft",
  title: "Create caption draft",
  description: "Create a new caption draft for the signed-in user. Returns the validated draft record which the user's app applies to the Studio and caption library on next open.",
  inputSchema: {
    title: z2.string().min(1).max(120).describe("Short title for the draft."),
    body: z2.string().min(1).max(4e3).describe("Caption body text."),
    hashtags: z2.array(z2.string()).optional().describe("Hashtags without leading #."),
    platformIds: z2.array(z2.string()).optional().describe("Target platform ids.")
  },
  annotations: {
    readOnlyHint: false,
    destructiveHint: false,
    openWorldHint: false
  },
  handler: (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const draft = {
      id: crypto.randomUUID(),
      title: input.title,
      body: input.body,
      hashtags: input.hashtags ?? [],
      platformIds: input.platformIds ?? [],
      tags: [],
      status: "pending-approval",
      createdAt: (/* @__PURE__ */ new Date()).toISOString(),
      source: "mcp:create_caption_draft",
      userId: ctx.getUserId()
    };
    return {
      content: [
        {
          type: "text",
          text: `Proposed caption draft "${input.title}". The user must approve it inside the app before it appears in their library.`
        }
      ],
      structuredContent: { draft, needsApproval: true }
    };
  }
});

// src/lib/mcp/tools/get-user-profile.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_user_profile_default = defineTool7({
  name: "get_user_profile",
  title: "Get user profile",
  description: "Return the signed-in SMM app user's profile (id, email, client, claims). Agents should call this first so their suggestions can be tailored to the user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const claims = ctx.getClaims?.() ?? {};
    const profile = {
      userId: ctx.getUserId(),
      email: ctx.getUserEmail(),
      clientId: ctx.getClientId(),
      displayName: claims.name ?? ctx.getUserEmail() ?? null,
      role: claims.role ?? "authenticated",
      locale: claims.locale ?? null,
      timezone: claims.timezone ?? null,
      note: "Extended profile fields live in the user's browser today. Ask them to open /dashboard/settings for full profile."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: profile
    };
  }
});

// src/lib/mcp/tools/get-automation-settings.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_automation_settings_default = defineTool8({
  name: "get_automation_settings",
  title: "Get automation settings",
  description: "Return the signed-in user's current SMM automation settings (engagement bot posture, notification channels, approval requirements, active platforms). Agents should call this before proposing actions so they respect the user's guardrails.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const settings = {
      userId: ctx.getUserId(),
      approval: {
        captionDraftsRequireApproval: true,
        scheduledPostsRequireApproval: true,
        note: "Write-capable MCP tools always propose items into the app's approval queue. The user reviews and approves in /dashboard/activity/mcp."
      },
      engagementBot: {
        posture: "conservative",
        autoReply: false,
        autoFollowBack: false,
        dailyActionCap: 100
      },
      notifications: {
        channels: ["inapp", "email"],
        digest: "weekly"
      },
      scheduling: {
        defaultLeadMinutes: 60,
        defaultIntervalMinutes: 15,
        timezone: "browser-local"
      },
      note: "Detailed per-event / per-platform preferences are stored in the user's browser (smmpilot:settings:*). Ask them to open /dashboard/settings for full settings."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(settings, null, 2) }],
      structuredContent: settings
    };
  }
});

// src/lib/mcp/tools/list-competitors.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";

// src/lib/mcp/helpers.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.5";
function edgeSupabase(ctx) {
  const token = typeof ctx.getToken === "function" ? ctx.getToken() : void 0;
  const deno = globalThis.Deno;
  const url = "https://ntbtbzssdwkbrfcmqyfc.supabase.co";
  const key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50YnRienNzZHdrYnJmY21xeWZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQwOTgwMzYsImV4cCI6MjA5OTY3NDAzNn0.XrUg247n7k82LNwnvHSaB-ftEnm0-J9umSWScQlfAhw";
  return createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false },
    global: {
      headers: token ? { Authorization: `Bearer ${token}` } : {}
    }
  });
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    return {
      ok: false,
      content: [{ type: "text", text: "Not authenticated. Connect your account via OAuth to use this tool." }],
      isError: true
    };
  }
  return { ok: true };
}
function tableResult(rows, summary) {
  const text = summary ? `${summary}

` : "";
  return {
    content: [{ type: "text", text: text + JSON.stringify(rows, null, 2) }],
    structuredContent: rows
  };
}

// src/lib/mcp/tools/list-competitors.ts
var list_competitors_default = defineTool9({
  name: "list_competitors",
  title: "List tracked competitors",
  description: "List the signed-in user's tracked competitors across all platforms (Instagram, TikTok, YouTube, X, LinkedIn, Threads, Reddit, Bluesky and more). Returns handle, platform, display name, status and follower count.",
  inputSchema: {
    platform: z3.string().optional().describe("Optional platform filter (e.g. instagram, github).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    const auth2 = requireAuth(ctx);
    if (!auth2.ok) return auth2;
    const db = edgeSupabase(ctx);
    let q = db.from("competitors").select("id, handle, platform, display_name, notes, data, created_at").eq("user_id", ctx.getUserId());
    if (input.platform) q = q.eq("platform", input.platform.toLowerCase());
    const { data, error } = await q.order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    return tableResult(data ?? [], `${(data ?? []).length} tracked competitor(s)`);
  }
});

// src/lib/mcp/tools/add-competitor.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
var add_competitor_default = defineTool10({
  name: "add_competitor",
  title: "Track a competitor",
  description: "Start tracking a competitor for the signed-in user. Pass the platform (instagram, tiktok, youtube, twitter, linkedin, facebook, threads, pinterest, reddit, bluesky) and their handle/username. Write tools require user approval inside the app.",
  inputSchema: {
    platform: z4.string().describe("Platform the competitor is on (e.g. instagram, github)."),
    handle: z4.string().describe("The competitor's handle or username on that platform."),
    displayName: z4.string().optional().describe("Optional display name."),
    notes: z4.string().optional().describe("Optional note about this competitor.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const auth2 = requireAuth(ctx);
    if (!auth2.ok) return auth2;
    const db = edgeSupabase(ctx);
    const row = {
      user_id: ctx.getUserId(),
      platform: input.platform.toLowerCase(),
      handle: input.handle.trim(),
      display_name: input.displayName?.trim() || null,
      notes: input.notes?.trim() || null,
      data: { status: "tracking" }
    };
    const { data, error } = await db.from("competitors").insert(row).select("id, handle, platform").maybeSingle();
    if (error) {
      if (String(error.code ?? "").startsWith("23")) {
        return { content: [{ type: "text", text: "This competitor is already being tracked." }], isError: false };
      }
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return tableResult(data ?? {}, `Now tracking ${input.handle} on ${input.platform}.`);
  }
});

// src/lib/mcp/tools/list-rss-feeds.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_rss_feeds_default = defineTool11({
  name: "list_rss_feeds",
  title: "List RSS feeds",
  description: "List the signed-in user's RSS automation feeds with their URL, poll interval, last fetch status, item counts, target platforms and errors. Use this before proposing any RSS-related action.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const auth2 = requireAuth(ctx);
    if (!auth2.ok) return auth2;
    const db = edgeSupabase(ctx);
    const { data, error } = await db.from("rss_feeds").select("id, url, title, target_platforms, filter_keywords, exclude_keywords, auto_publish, poll_interval_minutes, last_fetched_at, last_status, last_error, active").eq("owner_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    return tableResult(data ?? [], `${(data ?? []).length} RSS feed(s)`);
  }
});

// src/lib/mcp/tools/list-notifications.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^3.25.76";
var list_notifications_default = defineTool12({
  name: "list_notifications",
  title: "List notifications",
  description: "List the signed-in user's recent in-app notifications (engagement, milestones, alerts, reminders, system) with severity and read state. Use this to check for alerts, sync failures or milestone updates.",
  inputSchema: {
    limit: z5.number().int().min(1).max(50).optional().describe("Number of notifications to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    const auth2 = requireAuth(ctx);
    if (!auth2.ok) return auth2;
    const limit = Math.min(50, Math.max(1, Number(input.limit ?? 10) || 10));
    const db = edgeSupabase(ctx);
    const { data, error } = await db.from("notifications").select("id, type, severity, title, message, action_url, read_at, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    const unread = (data ?? []).filter((n) => !n.read_at).length;
    return tableResult(data ?? [], `${(data ?? []).length} notification(s), ${unread} unread`);
  }
});

// src/lib/mcp/tools/get-referral-status.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_referral_status_default = defineTool13({
  name: "get_referral_status",
  title: "Get referral status",
  description: "Return the signed-in user's referral program status: their share code and link, lifetime referral credits earned, and how many referred signups have upgraded to a paid plan.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const auth2 = requireAuth(ctx);
    if (!auth2.ok) return auth2;
    const userId = ctx.getUserId();
    const db = edgeSupabase(ctx);
    const [{ data: profile }, { data: referrals }, { data: events }] = await Promise.all([
      db.from("profiles").select("referral_code, referred_by").eq("id", userId).maybeSingle(),
      db.from("referrals").select("id, referred_user_id, plan, credits_awarded, rewarded_at").eq("referrer_id", userId).order("rewarded_at", { ascending: false }),
      db.from("credit_events").select("delta").eq("user_id", userId).eq("kind", "referral")
    ]);
    const totalEarned = (events ?? []).reduce((sum, e) => sum + Number(e.delta ?? 0), 0);
    const payload = {
      referralCode: profile?.referral_code ?? null,
      referralLink: profile?.referral_code ? `https://smmsaas.com/referral/${profile.referral_code}` : null,
      totalCreditsEarned: totalEarned,
      paidReferrals: (referrals ?? []).length,
      referredBy: profile?.referred_by ?? null,
      referrals: referrals ?? []
    };
    return tableResult(payload, payload.referralCode ? `Share code: ${payload.referralCode}` : "No referral code yet.");
  }
});

// src/lib/mcp/tools/get-credits.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_credits_default = defineTool14({
  name: "get_credits",
  title: "Get AI credit balance",
  description: "Return the signed-in user's AI credit balance (remaining, monthly allowance, used this month, purchased) plus their recent credit ledger events. Use this before recommending any credit-consuming action.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const auth2 = requireAuth(ctx);
    if (!auth2.ok) return auth2;
    const userId = ctx.getUserId();
    const db = edgeSupabase(ctx);
    const [{ data: bal }, { data: events }] = await Promise.all([
      db.from("credit_balances").select("included, purchased, used, cap, renews_at").eq("user_id", userId).maybeSingle(),
      db.from("credit_events").select("kind, delta, label, meta, created_at").eq("user_id", userId).order("created_at", { ascending: false }).limit(15)
    ]);
    const included = Number(bal?.included ?? 0);
    const purchased = Number(bal?.purchased ?? 0);
    const used = Number(bal?.used ?? 0);
    const payload = {
      remaining: Math.max(0, included + purchased - used),
      monthlyAllowance: Number(bal?.cap ?? included) || included,
      usedThisMonth: used,
      purchased,
      renewsAt: bal?.renews_at ?? null,
      recentEvents: events ?? []
    };
    return tableResult(payload, `${payload.remaining} credits remaining`);
  }
});

// src/lib/mcp/index.ts
var projectRef = "ntbtbzssdwkbrfcmqyfc";
var mcp_default = defineMcp({
  name: "smm-app-mcp",
  title: "SMM App MCP",
  version: "0.4.0",
  instructions: "Tools for the SMM app. Start with `get_user_profile` and `get_automation_settings` to tailor actions to the user. Use `whoami` for identity, `list_platforms` for supported networks, `list_scheduled_posts` / `queue_cross_platform_post` for the publish queue, `list_captions` / `create_caption_draft` for the caption library, `list_competitors` / `add_competitor` for competitive tracking, `list_rss_feeds` for RSS automation, `list_notifications` for alerts, `get_credits` for the AI credit balance and `get_referral_status` for the referral program. Write tools require user approval inside the app.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    get_user_profile_default,
    get_automation_settings_default,
    list_platforms_default,
    list_scheduled_posts_default,
    queue_cross_platform_post_default,
    list_captions_default,
    create_caption_draft_default,
    list_competitors_default,
    add_competitor_default,
    list_rss_feeds_default,
    list_notifications_default,
    get_referral_status_default,
    get_credits_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
